---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scaling.my.domain
  resources:
  - scalingrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scaling.my.domain
  resources:
  - scalingrules/finalizers
  verbs:
  - update
- apiGroups:
  - scaling.my.domain
  resources:
  - scalingrules/status
  verbs:
  - get
  - patch
  - update
