# This rule is not used by the project nats-scaler itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to scaling.my.domain resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nats-scaler
    app.kubernetes.io/managed-by: kustomize
  name: scalingrule-viewer-role
rules:
- apiGroups:
  - scaling.my.domain
  resources:
  - scalingrules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scaling.my.domain
  resources:
  - scalingrules/status
  verbs:
  - get
